
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
      # target: backend-builder
    ports:
      - "8000:8080"
    env_file:
      - .env
    depends_on:
      - db
    

  # frontend:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #     target: frontend-builder
  #   ports:
  #     - "3000:3000"
  #   working_dir: /app/web
  #   command: ["npm", "run", "dev"]

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=myapp
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/seed_db.sql:/docker-entrypoint-initdb.d/seed_db.sql
    
volumes:
  postgres_data: