
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
      target: backend-builder
    ports:
      - "8000:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=myapp
      - DB_USER=user
      - DB_PASSWORD=password
    depends_on:
      - db
    

  # frontend:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #     target: frontend-builder
  #   ports:
  #     - "3000:3000"
  #   working_dir: /app/web
  #   command: ["npm", "run", "dev"]

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=myapp
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
volumes:
  postgres_data: