services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: backend-dev
    ports:
      - "8000:8080"
    volumes:
      - .:/app
      - ./sensitive_fields.yaml:/app/cmd/sensitive_fields.yaml
    env_file:
      - .env
    depends_on:
      - db
    logging:  # <-- Added logging config to test
      driver: json-file
      options:
        max-size: "10m"  # Rotate at 10MB
        max-file: "3"     # Keep 3 log files
        tag: "backend"    # Adds service name to logs

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app/web
    working_dir: /app/web
    command: ["npm", "run", "dev"]
    depends_on:
      - backend
    logging:  
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"   
        tag: "fronted'"  

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=myapp
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/seed_db.sql:/docker-entrypoint-initdb.d/seed_db.sql
    logging:  
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"   
        tag: "postgres"  

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
    logging:  
      driver: json-file
      options:
        max-size: "5m"
        max-file: "1" 

  pgweb:
    image: sosedoff/pgweb
    ports:
      - "8082:8081"
    environment:
      - PGWEB_DATABASE_URL=postgres://user:password@db:5432/myapp?sslmode=disable
    depends_on:
      - db
    logging:  
      driver: json-file
      options:
        max-size: "5m"
        max-file: "1" 

  crawler:
    build:
      context: ./crawler
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    depends_on:
      - backend
    volumes:
      - ./crawler:/app
    # command: ["node", "dist/server.js"]
    logging:  
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
        tag: "crawler"


volumes:
  postgres_data:
